### ISSUE TITLE
Occasional 500 errors when looking at results page

### ISSUE THREAD

**Issue by jessebrennan** [thefreeguide/sccountyresources#26]
This only seems to happen if the page hasn't been queried in a little while (and only when deployed). I'll post a stack trace soon.

```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/sccalendar/views.py", line 76, in search_week
    return search(request, now.year, now.month, now.day, 'week')
  File "/srv/sccalendar/views.py", line 166, in search
    daily_events.append(api_call(services, locations, api_params))
  File "/srv/sccalendar/views.py", line 123, in api_call
    var_map[services].get_events(api_params)))
  File "/srv/sccalendar/google_calendar.py", line 179, in get_events
    for e in self.get_raw_events(api_params=api_params):
  File "/srv/sccalendar/google_calendar.py", line 160, in get_raw_events
    resp = self.service.events().list(calendarId=self.calendar_id, **api_params).execute()
  File "/env/lib/python3.7/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/env/lib/python3.7/site-packages/googleapiclient/http.py", line 836, in execute
    method=str(self.method), body=self.body, headers=self.headers)
  File "/env/lib/python3.7/site-packages/googleapiclient/http.py", line 167, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/env/lib/python3.7/site-packages/google_auth_httplib2.py", line 198, in request
    uri, method, body=body, headers=request_headers, **kwargs)
  File "/env/lib/python3.7/site-packages/httplib2/__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/env/lib/python3.7/site-packages/httplib2/__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/env/lib/python3.7/site-packages/httplib2/__init__.py", line 1188, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/opt/python3.7/lib/python3.7/http/client.py", line 977, in send
    self.sock.sendall(data)
  File "/opt/python3.7/lib/python3.7/ssl.py", line 1015, in sendall
    v = self.send(byte_view[count:])
  File "/opt/python3.7/lib/python3.7/ssl.py", line 984, in send
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by jessebrennan** [comment]
Looks like this is the same thing. Solution is to use `httplib2shim`.

https://github.com/googleapis/google-cloud-python/issues/1214

**Comment by alecmcleod** [comment]
Reopening this issue. Experiencing a possibly related error with the following stacktrace:

`ConnectionResetError: [Errno 104] Connection reset by peer
at send (/opt/python3.7/lib/python3.7/ssl.py:984)
at sendall (/opt/python3.7/lib/python3.7/ssl.py:1015)
at send (/opt/python3.7/lib/python3.7/http/client.py:977)
at _send_output (/opt/python3.7/lib/python3.7/http/client.py:1016)
at endheaders (/opt/python3.7/lib/python3.7/http/client.py:1224)
at _send_request (/opt/python3.7/lib/python3.7/http/client.py:1275)
at request (/opt/python3.7/lib/python3.7/http/client.py:1229)
at _conn_request (/env/lib/python3.7/site-packages/httplib2/__init__.py:1502)
at _request (/env/lib/python3.7/site-packages/httplib2/__init__.py:1595)
at request (/env/lib/python3.7/site-packages/httplib2/__init__.py:1926)
at request (/env/lib/python3.7/site-packages/google_auth_httplib2.py:198)
at _retry_request (/env/lib/python3.7/site-packages/googleapiclient/http.py:167)
at execute (/env/lib/python3.7/site-packages/googleapiclient/http.py:836)
at positional_wrapper (/env/lib/python3.7/site-packages/oauth2client/_helpers.py:133)
at get_raw_events (/srv/sccalendar/google_calendar.py:162)
at get_events (/srv/sccalendar/google_calendar.py:181)
at api_call (/srv/sccalendar/views.py:158)
at search (/srv/sccalendar/views.py:180)
at search_day_noncomplete (/srv/sccalendar/views.py:120)
at _get_response (/env/lib/python3.7/site-packages/django/core/handlers/base.py:126)
at _get_response (/env/lib/python3.7/site-packages/django/core/handlers/base.py:128)
at inner (/env/lib/python3.7/site-packages/django/core/handlers/exception.py:35)`

It appears that the problem is coming from google_calendar, it is possible that inserting the httplib2shim patch in that file could resolve this problem. Currently waiting for comment from @jessebrennan  as to whether this is reasonable.
